var Excel={
	CreateManagerExamineToExcel:function(time,res){
		// - 设置文件属性
		var xmlstr="";
        xmlstr += "<Root WorksheetName='用车审批单' WorksheetTitle='用车审批单" + time + "' ExpandedColumnCount='28' DefaultColumnWidth='50' >";
        xmlstr += "     <Columns>";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"61\" />";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"61\"/>";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"61\" />";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"61\" />";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"61\" />";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"61\" />";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"61\" />";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"61\" />";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"61\" />";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"61\" />";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"61\" />";
        xmlstr += "     </Columns>";

        // - 样式属性
        xmlstr += "     <StyleSheet>";
        xmlstr += "         <Style ID=\"header\" >";
        xmlstr += "             <Alignment Vertical=\"Center\" Horizontal=\"Center\"  WrapText=\"1\" />";
        xmlstr += "             <Font FontName=\"Times New Roman\" Family=\"Roman\" Size=\"18\" Bold=\"1\"/>";
        xmlstr += "         </Style>";
        xmlstr += "         <Style ID=\"title\" >";
        xmlstr += "             <Alignment Horizontal=\"Center\" Vertical=\"Center\" WrapText=\"1\" />";
        xmlstr += "             <Borders>";
        xmlstr += "                 <Border Position=\"Bottom\" LineStyle=\"Continuous\" Weight=\"1\"/>";
        xmlstr += "                 <Border Position=\"Left\" LineStyle=\"Continuous\" Weight=\"1\"/>";
        xmlstr += "                 <Border Position=\"Right\" LineStyle=\"Continuous\" Weight=\"1\"/>";
        xmlstr += "                 <Border Position=\"Top\" LineStyle=\"Continuous\" Weight=\"1\"/>";
        xmlstr += "             </Borders>";
        xmlstr += "             <Font FontName=\"宋体\" CharSet=\"134\" Size=\"10\"/>";
        xmlstr += "         </Style>";
        xmlstr += "         <Style ID=\"cell_1\" >";
        xmlstr += "             <Alignment Horizontal=\"Center\" Vertical=\"Center\"  WrapText=\"1\"/>";
        xmlstr += "             <Borders>";
        xmlstr += "                 <Border Position=\"Bottom\"  LineStyle=\"Continuous\" Weight=\"1\"/>";
        xmlstr += "                 <Border Position=\"Left\" LineStyle=\"Continuous\" Weight=\"1\"/>";
        xmlstr += "                 <Border Position=\"Right\" LineStyle=\"Continuous\"  Weight=\"1\"/>";
        xmlstr += "                 <Border Position=\"Top\" LineStyle=\"Continuous\" Weight=\"1\"/>";
        xmlstr += "             </Borders>";
        xmlstr += "             <Font FontName=\"宋体\" CharSet=\"134\" Color=\"#000000\" />";
        xmlstr += "             <Interior/>";
        xmlstr += "         </Style>";
        xmlstr += "         <Style ID=\"cell_3\">";
        xmlstr += "             <Alignment  Vertical=\"Center\" WrapText=\"1\"/>";
        xmlstr += "             <Borders>";
        xmlstr += "                 <Border Position=\"Bottom\"  LineStyle=\"Continuous\" Weight=\"1\"/>";
        xmlstr += "                 <Border Position=\"Left\" LineStyle=\"Continuous\" Weight=\"1\"/>";
        xmlstr += "                 <Border Position=\"Right\" LineStyle=\"Continuous\"  Weight=\"1\"/>";
        xmlstr += "                 <Border Position=\"Top\" LineStyle=\"Continuous\" Weight=\"1\"/>";
        xmlstr += "             </Borders>";
        xmlstr += "             <Font FontName=\"宋体\" CharSet=\"134\" Color=\"#000000\" />";
        xmlstr += "             <Interior/>";
        xmlstr += "         </Style>";
        xmlstr += "         <Style ID=\"cell_2\">";
        xmlstr += "             <Alignment Vertical=\"Center\" WrapText=\"1\"/>";
        xmlstr += "             <Font FontName=\"宋体\" CharSet=\"134\" Color=\"#000000\"/>";
        xmlstr += "             <Interior/>";
        xmlstr += "             <NumberFormat Format=\"0.0\"/>";
        xmlstr += "         </Style>";
        xmlstr += "</StyleSheet>";
		
		// - 报表头（总头）
        xmlstr += "<Title>";
        xmlstr += "     <Row Height=\"30\">";
        xmlstr += "         <Cell MergeAcross=\"7\" StyleID=\"header\" >";
        xmlstr += "             <Data Type=\"String\">用车审批单</Data>";
        xmlstr += "         </Cell>";
        xmlstr += "     </Row>";
        xmlstr += "</Title>";

//		// 内容
        xmlstr += "<Contents>";
        xmlstr += "<Row Height=\"30\">";
		 // - 一个单元格(Cell)
		xmlstr += "     <Cell StyleID=\"cell_2\" MergeAcross=\"7\">";
		xmlstr += "         <Data Type=\"String\">&#160;出车时间：" + res.Time + "</Data>";
		xmlstr += "     </Cell>";
		xmlstr += "</Row>";
		// - 一行（Row）
		xmlstr += "<Row Height=\"30\">";
		 // - 一个单元格(Cell)
		xmlstr += "     <Cell StyleID=\"cell_1\" >";
		xmlstr += "         <Data Type=\"String\">用车单位</Data>";
		xmlstr += "     </Cell>";
		xmlstr += "     <Cell StyleID=\"cell_1\" MergeAcross=\"2\">";
		xmlstr += "         <Data Type=\"String\">" + res.UseDept + "</Data>";
		xmlstr += "     </Cell>";
		xmlstr += "     <Cell StyleID=\"cell_1\" MergeDown=\"1\">";
		xmlstr += "         <Data Type=\"String\">" + "批准首长" + "</Data>";
		xmlstr += "     </Cell>";
		xmlstr += "     <Cell StyleID=\"cell_1\" MergeDown=\"1\" MergeAcross=\"2\">";
		xmlstr += "         <Data Type=\"String\">" + res.Replies + "</Data>";
		xmlstr += "     </Cell>";
		xmlstr += "</Row>";
		
		xmlstr += "<Row Height=\"30\">";
		 // - 一个单元格(Cell)
		xmlstr += "     <Cell StyleID=\"cell_1\" >";
		xmlstr += "         <Data Type=\"String\">" + "出车单位" + "</Data>";
		xmlstr += "     </Cell>";
		xmlstr += "     <Cell StyleID=\"cell_1\" MergeAcross=\"2\">";
		xmlstr += "         <Data Type=\"String\">" + res.VehicleDept + "</Data>";
		xmlstr += "     </Cell>";
		xmlstr += "</Row>";
		xmlstr += "<Row Height=\"30\">";
		xmlstr += "     <Cell StyleID=\"cell_1\" >";
		xmlstr += "         <Data Type=\"String\">" + "出车事由" + "</Data>";
		xmlstr += "     </Cell>";
		xmlstr += "     <Cell StyleID=\"cell_1\" MergeAcross=\"2\">";
		xmlstr += "         <Data Type=\"String\">" + res.UseContent + "</Data>";
		xmlstr += "     </Cell>";
		xmlstr += "     <Cell StyleID=\"cell_1\" >";
		xmlstr += "         <Data Type=\"String\">" + "承办人" + "</Data>";
		xmlstr += "     </Cell>";
		xmlstr += "     <Cell StyleID=\"cell_1\" MergeAcross=\"2\">";
		xmlstr += "         <Data Type=\"String\">" + res.Contractor + "</Data>";
		xmlstr += "     </Cell>";
		xmlstr += "</Row>";
		xmlstr += "<Row Height=\"30\">";
		xmlstr += "     <Cell StyleID=\"cell_1\">";
		xmlstr += "         <Data Type=\"String\">" + "车型" + "</Data>";
		xmlstr += "     </Cell>";
		xmlstr += "     <Cell StyleID=\"cell_1\">";
		xmlstr += "         <Data Type=\"String\">" + res.VehicleModel + "</Data>";
		xmlstr += "     </Cell>";
		xmlstr += "     <Cell StyleID=\"cell_1\" >";
		xmlstr += "         <Data Type=\"String\">" + "车牌号" + "</Data>";
		xmlstr += "     </Cell>";
		xmlstr += "     <Cell StyleID=\"cell_1\">";
		xmlstr += "         <Data Type=\"String\">" + res.VehicleID + "</Data>";
		xmlstr += "     </Cell>";
		xmlstr += "     <Cell StyleID=\"cell_1\" >";
		xmlstr += "         <Data Type=\"String\">" + "带车人" + "</Data>";
		xmlstr += "     </Cell>";
		xmlstr += "     <Cell StyleID=\"cell_1\">";
		xmlstr += "         <Data Type=\"String\">" + res.Car_owner + "</Data>";
		xmlstr += "     </Cell>";
		xmlstr += "     <Cell StyleID=\"cell_1\" >";
		xmlstr += "         <Data Type=\"String\">" + "驾驶员" + "</Data>";
		xmlstr += "     </Cell>";
		xmlstr += "     <Cell StyleID=\"cell_1\">";
		xmlstr += "         <Data Type=\"String\">" + res.Driver + "</Data>";
		xmlstr += "     </Cell>";
		xmlstr += "</Row>";
		xmlstr += "<Row Height=\"30\">";
		xmlstr += "     <Cell StyleID=\"cell_1\" >";
		xmlstr += "         <Data Type=\"String\">" + "出车时间" + "</Data>";
		xmlstr += "     </Cell>";
		xmlstr += "     <Cell StyleID=\"cell_1\" MergeAcross=\"2\">";
		xmlstr += "         <Data Type=\"String\">" + res.out_time + "</Data>";
		xmlstr += "     </Cell>";
		xmlstr += "     <Cell StyleID=\"cell_1\" >";
		xmlstr += "         <Data Type=\"String\">" + "返回时间" + "</Data>";
		xmlstr += "     </Cell>";
		xmlstr += "     <Cell StyleID=\"cell_1\" MergeAcross=\"2\">";
		xmlstr += "         <Data Type=\"String\">" + res.in_time + "</Data>";
		xmlstr += "     </Cell>";
		xmlstr += "</Row>";
		xmlstr += "<Row Height=\"30\">";
		xmlstr += "     <Cell StyleID=\"cell_1\" >";
		xmlstr += "         <Data Type=\"String\">" + "行驶路线" + "</Data>";
		xmlstr += "     </Cell>";
		xmlstr += "     <Cell StyleID=\"cell_3\" MergeAcross=\"6\">";
		xmlstr += "         <Data Type=\"String\">" + res.Driving_route + "</Data>";
		xmlstr += "     </Cell>";
		xmlstr += "</Row>";
		xmlstr += "<Row Height=\"50\">";
		xmlstr += "     <Cell StyleID=\"cell_1\" >";
		xmlstr += "         <Data Type=\"String\">" + "备注" + "</Data>";
		xmlstr += "     </Cell>";
		xmlstr += "     <Cell StyleID=\"cell_3\" MergeAcross=\"6\">";
		xmlstr += "         <Data Type=\"String\">&#160;" + res.Remark + "</Data>";
		xmlstr += "     </Cell>";
		xmlstr += "</Row>";
		xmlstr += "</Contents>";
        xmlstr += "</Root>";
        $("#excelcontent").val(xmlstr);
        $("#excelform").submit();
	},
	CreateManagerBasicInfoToExcel:function(time,res){
		var xmlstr="";
        xmlstr += "<Root WorksheetName='车辆基础信息表' WorksheetTitle='车辆基础信息表" + time + "' ExpandedColumnCount='28' DefaultColumnWidth='50' >";
        xmlstr += "     <Columns>";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"30\" />";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"30\"/>";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"30\" />";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"40\" />";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"30\" />";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"40\" />";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"30\" />";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"30\" />";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"40\" />";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"20\" />";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"20\" />";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"20\"/>";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"20\" />";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"30\" />";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"40\" />";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"40\" />";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"40\" />";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"40\" />";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"40\" />";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"40\" />";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"40\" />";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"40\" />";
        xmlstr += "     </Columns>";

        // - 样式属性
        xmlstr += "     <StyleSheet>";
        xmlstr += "         <Style ID=\"header\" >";
        xmlstr += "             <Alignment Vertical=\"Center\" Horizontal=\"Center\"  WrapText=\"1\" />";
        xmlstr += "             <Font FontName=\"Times New Roman\" Family=\"Roman\" Size=\"18\" Bold=\"1\"/>";
        xmlstr += "         </Style>";
        xmlstr += "         <Style ID=\"title\" >";
        xmlstr += "             <Alignment Horizontal=\"Center\" Vertical=\"Center\" WrapText=\"1\" />";
        xmlstr += "             <Borders>";
        xmlstr += "                 <Border Position=\"Bottom\" LineStyle=\"Continuous\" Weight=\"1\"/>";
        xmlstr += "                 <Border Position=\"Left\" LineStyle=\"Continuous\" Weight=\"1\"/>";
        xmlstr += "                 <Border Position=\"Right\" LineStyle=\"Continuous\" Weight=\"1\"/>";
        xmlstr += "                 <Border Position=\"Top\" LineStyle=\"Continuous\" Weight=\"1\"/>";
        xmlstr += "             </Borders>";
        xmlstr += "             <Font FontName=\"宋体\" CharSet=\"134\" Size=\"10\"/>";
        xmlstr += "         </Style>";
        xmlstr += "         <Style ID=\"cell_1\" >";
        xmlstr += "             <Alignment Horizontal=\"Center\" Vertical=\"Center\"  WrapText=\"1\"/>";
        xmlstr += "             <Borders>";
        xmlstr += "                 <Border Position=\"Bottom\"  LineStyle=\"Continuous\" Weight=\"1\"/>";
        xmlstr += "                 <Border Position=\"Left\" LineStyle=\"Continuous\" Weight=\"1\"/>";
        xmlstr += "                 <Border Position=\"Right\" LineStyle=\"Continuous\"  Weight=\"1\"/>";
        xmlstr += "                 <Border Position=\"Top\" LineStyle=\"Continuous\" Weight=\"1\"/>";
        xmlstr += "             </Borders>";
        xmlstr += "             <Font FontName=\"宋体\" CharSet=\"134\" Color=\"#000000\" />";
        xmlstr += "             <Interior/>";
        xmlstr += "         </Style>";
        xmlstr += "         <Style ID=\"cell_3\">";
        xmlstr += "             <Alignment  Vertical=\"Center\" WrapText=\"1\"/>";
        xmlstr += "             <Borders>";
        xmlstr += "                 <Border Position=\"Bottom\"  LineStyle=\"Continuous\" Weight=\"1\"/>";
        xmlstr += "                 <Border Position=\"Left\" LineStyle=\"Continuous\" Weight=\"1\"/>";
        xmlstr += "                 <Border Position=\"Right\" LineStyle=\"Continuous\"  Weight=\"1\"/>";
        xmlstr += "                 <Border Position=\"Top\" LineStyle=\"Continuous\" Weight=\"1\"/>";
        xmlstr += "             </Borders>";
        xmlstr += "             <Font FontName=\"宋体\" CharSet=\"134\" Color=\"#000000\" />";
        xmlstr += "             <Interior/>";
        xmlstr += "         </Style>";
        xmlstr += "         <Style ID=\"cell_2\">";
        xmlstr += "             <Alignment Vertical=\"Center\" WrapText=\"1\"/>";
        xmlstr += "             <Font FontName=\"宋体\" CharSet=\"134\" Color=\"#000000\"/>";
        xmlstr += "             <Interior/>";
        xmlstr += "             <NumberFormat Format=\"0.0\"/>";
        xmlstr += "         </Style>";
        xmlstr += "</StyleSheet>";
		
		// - 报表头（总头）
        xmlstr += "<Title>";
        xmlstr += "     <Row Height=\"28\">";
        xmlstr += "         <Cell MergeAcross=\"21\" StyleID=\"header\" >";
        xmlstr += "             <Data Type=\"String\">车辆基础信息表</Data>";
        xmlstr += "         </Cell>";
        xmlstr += "     </Row>";
        // - 报表头（分部）
        xmlstr += "     <Row Height=\"30\" AutoFitHeight=\"1\">";
        xmlstr += "         <Cell StyleID=\"title\">";
        xmlstr += "             <Data Type=\"String\">序号</Data>";
        xmlstr += "         </Cell>";
        xmlstr += "         <Cell StyleID=\"title\">";
        xmlstr += "             <Data Type=\"String\">车牌号</Data>";
        xmlstr += "         </Cell>";
        xmlstr += "         <Cell StyleID=\"title\">";
        xmlstr += "             <Data Type=\"String\">车架号</Data>";
        xmlstr += "         </Cell>";
        xmlstr += "         <Cell StyleID=\"title\">";
        xmlstr += "             <Data Type=\"String\">发动机序列号</Data>";
        xmlstr += "         </Cell>";
        xmlstr += "         <Cell StyleID=\"title\">";
        xmlstr += "             <Data Type=\"String\">车型</Data>";
        xmlstr += "         </Cell>";
        xmlstr += "         <Cell StyleID=\"title\">";
        xmlstr += "             <Data Type=\"String\">燃料种类</Data>";
        xmlstr += "         </Cell>";
        xmlstr += "         <Cell StyleID=\"title\">";
        xmlstr += "             <Data Type=\"String\">车辆颜色</Data>";
        xmlstr += "         </Cell>";
        xmlstr += "         <Cell StyleID=\"title\">";
        xmlstr += "             <Data Type=\"String\">座位数</Data>";
        xmlstr += "         </Cell>";
        xmlstr += "         <Cell StyleID=\"title\">";
        xmlstr += "             <Data Type=\"String\">配发时间</Data>";
        xmlstr += "         </Cell>";
        xmlstr += "         <Cell StyleID=\"title\">";
        xmlstr += "             <Data Type=\"String\">里程（km/h）</Data>";
        xmlstr += "         </Cell>";
        xmlstr += "         <Cell StyleID=\"title\">";
        xmlstr += "             <Data Type=\"String\">油耗（L）</Data>";
        xmlstr += "         </Cell>";
        xmlstr += "         <Cell StyleID=\"title\">";
        xmlstr += "             <Data Type=\"String\">油箱容积（L）</Data>";
        xmlstr += "         </Cell>";
        xmlstr += "         <Cell StyleID=\"title\">";
        xmlstr += "             <Data Type=\"String\">最大载重（Kg）</Data>";
        xmlstr += "         </Cell>";
        xmlstr += "         <Cell StyleID=\"title\">";
        xmlstr += "             <Data Type=\"String\">总质量（Kg）</Data>";
        xmlstr += "         </Cell>";
        xmlstr += "         <Cell StyleID=\"title\">";
        xmlstr += "             <Data Type=\"String\">外廓尺寸（L*W*H）</Data>";
        xmlstr += "         </Cell>";
        xmlstr += "         <Cell StyleID=\"title\">";
        xmlstr += "             <Data Type=\"String\">车属单位</Data>";
        xmlstr += "         </Cell>";
        xmlstr += "         <Cell StyleID=\"title\">";
        xmlstr += "             <Data Type=\"String\">车辆管理部门</Data>";
        xmlstr += "         </Cell>";
        xmlstr += "         <Cell StyleID=\"title\">";
        xmlstr += "             <Data Type=\"String\">车辆管理人员</Data>";
        xmlstr += "         </Cell>";
        xmlstr += "         <Cell StyleID=\"title\">";
        xmlstr += "             <Data Type=\"String\">入档日期</Data>";
        xmlstr += "         </Cell>";
        xmlstr += "         <Cell StyleID=\"title\">";
        xmlstr += "             <Data Type=\"String\">负责单位主管</Data>";
        xmlstr += "         </Cell>";
        xmlstr += "         <Cell StyleID=\"title\">";
        xmlstr += "             <Data Type=\"String\">第一负责人</Data>";
        xmlstr += "         </Cell>";
        xmlstr += "         <Cell StyleID=\"title\">";
        xmlstr += "             <Data Type=\"String\">第二负责人</Data>";
        xmlstr += "         </Cell>";
        xmlstr += "     </Row>";
        xmlstr += "</Title>";

		// 内容
        xmlstr += "<Contents>";
        for(var i=0;i<res.length;i++){
			xmlstr += "     <Row Height=\"30\" AutoFitHeight=\"1\">";
	        xmlstr += "         <Cell StyleID=\"cell_1\">";
	        xmlstr += "             <Data Type=\"Number\">"+(i+1)+"</Data>";
	        xmlstr += "         </Cell>";
	        xmlstr += "         <Cell StyleID=\"cell_1\">";
	        xmlstr += "             <Data Type=\"String\">"+res[i].ID+"</Data>";
	        xmlstr += "         </Cell>";
	        xmlstr += "         <Cell StyleID=\"cell_1\">";
	        xmlstr += "             <Data Type=\"String\">"+res[i].VIN_NO+"</Data>";
	        xmlstr += "         </Cell>";
	        xmlstr += "         <Cell StyleID=\"cell_1\">";
	        xmlstr += "             <Data Type=\"String\">"+res[i].ENGINE_SERIAL_NUMBER+"</Data>";
	        xmlstr += "         </Cell>";
	        xmlstr += "         <Cell StyleID=\"cell_1\">";
	        xmlstr += "             <Data Type=\"String\">"+res[i].Model+"</Data>";
	        xmlstr += "         </Cell>";
	        xmlstr += "         <Cell StyleID=\"cell_1\">";
	        xmlstr += "             <Data Type=\"String\">"+res[i].Fuel_Index+"</Data>";
	        xmlstr += "         </Cell>";
	        xmlstr += "         <Cell StyleID=\"cell_1\">";
	        xmlstr += "             <Data Type=\"String\">"+res[i].Color+"</Data>";
	        xmlstr += "         </Cell>";
	        xmlstr += "         <Cell StyleID=\"cell_1\">";
	        xmlstr += "             <Data Type=\"Number\">"+res[i].Seating+"</Data>";
	        xmlstr += "         </Cell>";
	        xmlstr += "         <Cell StyleID=\"cell_1\">";
	        xmlstr += "             <Data Type=\"String\">"+res[i].Time.substr(0,10)+"</Data>";
	        xmlstr += "         </Cell>";
	        xmlstr += "         <Cell StyleID=\"cell_1\">";
	        xmlstr += "             <Data Type=\"Number\">"+res[i].Mileage+"</Data>";
	        xmlstr += "         </Cell>";
	        xmlstr += "         <Cell StyleID=\"cell_1\">";
	        xmlstr += "             <Data Type=\"Number\">"+res[i].Oil_Wear+"</Data>";
	        xmlstr += "         </Cell>";
	        xmlstr += "         <Cell StyleID=\"cell_1\">";
	        xmlstr += "             <Data Type=\"Number\">"+res[i].TankSize+"</Data>";
	        xmlstr += "         </Cell>";
	        xmlstr += "         <Cell StyleID=\"cell_1\">";
	        xmlstr += "             <Data Type=\"Number\">"+res[i].Maximum_Load+"</Data>";
	        xmlstr += "         </Cell>";
	        xmlstr += "         <Cell StyleID=\"cell_1\">";
	        xmlstr += "             <Data Type=\"Number\">"+res[i].Total_mass+"</Data>";
	        xmlstr += "         </Cell>";
	        xmlstr += "         <Cell StyleID=\"cell_1\">";
	        xmlstr += "             <Data Type=\"String\">"+res[i].Overall_Dimension+"</Data>";
	        xmlstr += "         </Cell>";
	        xmlstr += "         <Cell StyleID=\"cell_1\">";
	        xmlstr += "             <Data Type=\"String\">"+res[i].V_Dept+"</Data>";
	        xmlstr += "         </Cell>";
	        xmlstr += "         <Cell StyleID=\"cell_1\">";
	        xmlstr += "             <Data Type=\"String\">"+res[i].V_Dept_Manager+"</Data>";
	        xmlstr += "         </Cell>";
	        xmlstr += "         <Cell StyleID=\"cell_1\">";
	        xmlstr += "             <Data Type=\"String\">"+res[i].V_Employee_Manager+"</Data>";
	        xmlstr += "         </Cell>";
	        xmlstr += "         <Cell StyleID=\"cell_1\">";
	        xmlstr += "             <Data Type=\"String\">"+res[i].Register_Time+"</Data>";
	        xmlstr += "         </Cell>";
	        xmlstr += "         <Cell StyleID=\"cell_1\">";
	        xmlstr += "             <Data Type=\"String\">"+res[i].Responsible_Officer+"</Data>";
	        xmlstr += "         </Cell>";
	        xmlstr += "         <Cell StyleID=\"cell_1\">";
	        xmlstr += "             <Data Type=\"String\">"+res[i].FirstLeading_Person+"</Data>";
	        xmlstr += "         </Cell>";
	        xmlstr += "         <Cell StyleID=\"cell_1\">";
	        xmlstr += "             <Data Type=\"String\">"+res[i].SecondLeading_Person+"</Data>";
	        xmlstr += "         </Cell>";
	        xmlstr += "     </Row>";
		}
		xmlstr += "</Contents>"
        xmlstr += "</Root>";
        $("#excelcontent").val(xmlstr);
        $("#excelform").submit();
	},
	CreateManagerRegisterToExcel:function(time,res){
		var xmlstr="";
        xmlstr += "<Root WorksheetName='车辆维修保养登记表' WorksheetTitle='车辆维修保养登记表" + time + "' ExpandedColumnCount='28' DefaultColumnWidth='50' >";
        xmlstr += "     <Columns>";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"40\" />";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"50\"/>";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"40\" />";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"60\" />";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"150\" />";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"150\" />";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"60\" />";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"40\" />";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"40\" />";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"40\" />";
        xmlstr += "     </Columns>";
        // - 样式属性
        xmlstr += "     <StyleSheet>";
        xmlstr += "         <Style ID=\"header\" >";
        xmlstr += "             <Alignment Vertical=\"Center\" Horizontal=\"Center\"  WrapText=\"1\" />";
        xmlstr += "             <Font FontName=\"Times New Roman\" Family=\"Roman\" Size=\"18\" Bold=\"1\"/>";
        xmlstr += "         </Style>";
        xmlstr += "         <Style ID=\"title\" >";
        xmlstr += "             <Alignment Horizontal=\"Center\" Vertical=\"Center\" WrapText=\"1\" />";
        xmlstr += "             <Borders>";
        xmlstr += "                 <Border Position=\"Bottom\" LineStyle=\"Continuous\" Weight=\"1\"/>";
        xmlstr += "                 <Border Position=\"Left\" LineStyle=\"Continuous\" Weight=\"1\"/>";
        xmlstr += "                 <Border Position=\"Right\" LineStyle=\"Continuous\" Weight=\"1\"/>";
        xmlstr += "                 <Border Position=\"Top\" LineStyle=\"Continuous\" Weight=\"1\"/>";
        xmlstr += "             </Borders>";
        xmlstr += "             <Font FontName=\"宋体\" CharSet=\"134\" Size=\"10\"/>";
        xmlstr += "         </Style>";
        xmlstr += "         <Style ID=\"cell_1\" >";
        xmlstr += "             <Alignment Horizontal=\"Center\" Vertical=\"Center\"  WrapText=\"1\"/>";
        xmlstr += "             <Borders>";
        xmlstr += "                 <Border Position=\"Bottom\"  LineStyle=\"Continuous\" Weight=\"1\"/>";
        xmlstr += "                 <Border Position=\"Left\" LineStyle=\"Continuous\" Weight=\"1\"/>";
        xmlstr += "                 <Border Position=\"Right\" LineStyle=\"Continuous\"  Weight=\"1\"/>";
        xmlstr += "                 <Border Position=\"Top\" LineStyle=\"Continuous\" Weight=\"1\"/>";
        xmlstr += "             </Borders>";
        xmlstr += "             <Font FontName=\"宋体\" CharSet=\"134\" Color=\"#000000\" />";
        xmlstr += "             <Interior/>";
        xmlstr += "         </Style>";
        xmlstr += "         <Style ID=\"cell_3\">";
        xmlstr += "             <Alignment  Vertical=\"Center\" WrapText=\"1\"/>";
        xmlstr += "             <Borders>";
        xmlstr += "                 <Border Position=\"Bottom\"  LineStyle=\"Continuous\" Weight=\"1\"/>";
        xmlstr += "                 <Border Position=\"Left\" LineStyle=\"Continuous\" Weight=\"1\"/>";
        xmlstr += "                 <Border Position=\"Right\" LineStyle=\"Continuous\"  Weight=\"1\"/>";
        xmlstr += "                 <Border Position=\"Top\" LineStyle=\"Continuous\" Weight=\"1\"/>";
        xmlstr += "             </Borders>";
        xmlstr += "             <Font FontName=\"宋体\" CharSet=\"134\" Color=\"#000000\" />";
        xmlstr += "             <Interior/>";
        xmlstr += "         </Style>";
        xmlstr += "         <Style ID=\"cell_2\">";
        xmlstr += "             <Alignment Vertical=\"Center\" WrapText=\"1\"/>";
        xmlstr += "             <Font FontName=\"宋体\" CharSet=\"134\" Color=\"#000000\"/>";
        xmlstr += "             <Interior/>";
        xmlstr += "             <NumberFormat Format=\"0.0\"/>";
        xmlstr += "         </Style>";
        xmlstr += "</StyleSheet>";
		
		// - 报表头（总头）
        xmlstr += "<Title>";
        xmlstr += "     <Row Height=\"28\" >";
        xmlstr += "         <Cell MergeAcross=\"10\" StyleID=\"header\" >";
        xmlstr += "             <Data Type=\"String\">车辆维修保养登记表</Data>";
        xmlstr += "         </Cell>";
        xmlstr += "     </Row>";
        // - 报表头（分部）
        xmlstr += "     <Row Height=\"30\" >";
        xmlstr += "         <Cell StyleID=\"title\">";
        xmlstr += "             <Data Type=\"String\">序号</Data>";
        xmlstr += "         </Cell>";
        xmlstr += "         <Cell StyleID=\"title\">";
        xmlstr += "             <Data Type=\"String\">车辆牌号</Data>";
        xmlstr += "         </Cell>";
        xmlstr += "         <Cell StyleID=\"title\">";
        xmlstr += "             <Data Type=\"String\">车架号</Data>";
        xmlstr += "         </Cell>";
        xmlstr += "         <Cell StyleID=\"title\">";
        xmlstr += "             <Data Type=\"String\">日期</Data>";
        xmlstr += "         </Cell>";
        xmlstr += "         <Cell StyleID=\"title\">";
        xmlstr += "             <Data Type=\"String\">维修原因</Data>";
        xmlstr += "         </Cell>";
        xmlstr += "         <Cell StyleID=\"title\">";
        xmlstr += "             <Data Type=\"String\">保养维护内容</Data>";
        xmlstr += "         </Cell>";
        xmlstr += "         <Cell StyleID=\"title\">";
        xmlstr += "             <Data Type=\"String\">预计下次保养日期</Data>";
        xmlstr += "         </Cell>";
        xmlstr += "         <Cell StyleID=\"title\">";
        xmlstr += "             <Data Type=\"String\">修理工</Data>";
        xmlstr += "         </Cell>";
        xmlstr += "         <Cell StyleID=\"title\">";
        xmlstr += "             <Data Type=\"String\">驾驶员</Data>";
        xmlstr += "         </Cell>";
        xmlstr += "         <Cell StyleID=\"title\">";
        xmlstr += "             <Data Type=\"String\">费用</Data>";
        xmlstr += "         </Cell>";
        xmlstr += "         <Cell StyleID=\"title\">";
        xmlstr += "             <Data Type=\"String\">登记人</Data>";
        xmlstr += "         </Cell>";
        xmlstr += "     </Row>";
        xmlstr += "</Title>";

		// 内容
        xmlstr += "<Contents>";
        for(var i=0;i<res.length;i++){
			xmlstr += "     <Row Height=\"30\" >";
	        xmlstr += "         <Cell StyleID=\"cell_1\">";
	        xmlstr += "             <Data Type=\"Number\">"+(i+1)+"</Data>";
	        xmlstr += "         </Cell>";
	        xmlstr += "         <Cell StyleID=\"cell_1\">";
	        xmlstr += "             <Data Type=\"String\">"+res[i].ID+"</Data>";
	        xmlstr += "         </Cell>";
	        xmlstr += "         <Cell StyleID=\"cell_1\">";
	        xmlstr += "             <Data Type=\"String\">"+res[i].VIN_NO+"</Data>";
	        xmlstr += "         </Cell>";
	        xmlstr += "         <Cell StyleID=\"cell_1\">";
	        xmlstr += "             <Data Type=\"String\">"+res[i].Date+"</Data>";
	        xmlstr += "         </Cell>";
	        xmlstr += "         <Cell StyleID=\"cell_1\">";
	        xmlstr += "             <Data Type=\"String\">"+res[i].MainTain_Reason+"</Data>";
	        xmlstr += "         </Cell>";
	        xmlstr += "         <Cell StyleID=\"cell_1\">";
	        xmlstr += "             <Data Type=\"String\">"+res[i].MainTain_Content+"</Data>";
	        xmlstr += "         </Cell>";
	        xmlstr += "         <Cell StyleID=\"cell_1\">";
	        xmlstr += "             <Data Type=\"String\">"+res[i].Next_MainTain_Date+"</Data>";
	        xmlstr += "         </Cell>";
	        xmlstr += "         <Cell StyleID=\"cell_1\">";
	        xmlstr += "             <Data Type=\"String\">"+res[i].Repairman+"</Data>";
	        xmlstr += "         </Cell>";
	        xmlstr += "         <Cell StyleID=\"cell_1\">";
	        xmlstr += "             <Data Type=\"String\">"+res[i].Driver+"</Data>";
	        xmlstr += "         </Cell>";
	        xmlstr += "         <Cell StyleID=\"cell_1\">";
	        xmlstr += "             <Data Type=\"Number\">"+res[i].Cost+"</Data>";
	        xmlstr += "         </Cell>";
	        xmlstr += "         <Cell StyleID=\"cell_1\">";
	        xmlstr += "             <Data Type=\"String\">"+res[i].Registrant+"</Data>";
	        xmlstr += "         </Cell>";
	        xmlstr += "     </Row>";
		}
		xmlstr += "</Contents>"
        xmlstr += "</Root>";
        $("#excelcontent").val(xmlstr);
        $("#excelform").submit();
	},
	CreateManagerCountToExcel:function(time,res){
		var xmlstr="";
        xmlstr += "<Root WorksheetName='单车油耗统计表' WorksheetTitle='单车油耗统计表" + time + "' ExpandedColumnCount='28' DefaultColumnWidth='50' >";
        xmlstr += "     <Columns>";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"40\" />";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"80\"/>";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"80\" />";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"80\" />";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"80\" />";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"80\" />";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"80\" />";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"80\" />";
        xmlstr += "         <Column AutoFitWidth=\"0\" Width=\"80\" />";
        xmlstr += "     </Columns>";
        // - 样式属性
        xmlstr += "     <StyleSheet>";
        xmlstr += "         <Style ID=\"header\" >";
        xmlstr += "             <Alignment Vertical=\"Center\" Horizontal=\"Center\"  WrapText=\"1\" />";
        xmlstr += "             <Font FontName=\"Times New Roman\" Family=\"Roman\" Size=\"18\" Bold=\"1\"/>";
        xmlstr += "         </Style>";
        xmlstr += "         <Style ID=\"title\" >";
        xmlstr += "             <Alignment Horizontal=\"Center\" Vertical=\"Center\" WrapText=\"1\" />";
        xmlstr += "             <Borders>";
        xmlstr += "                 <Border Position=\"Bottom\" LineStyle=\"Continuous\" Weight=\"1\"/>";
        xmlstr += "                 <Border Position=\"Left\" LineStyle=\"Continuous\" Weight=\"1\"/>";
        xmlstr += "                 <Border Position=\"Right\" LineStyle=\"Continuous\" Weight=\"1\"/>";
        xmlstr += "                 <Border Position=\"Top\" LineStyle=\"Continuous\" Weight=\"1\"/>";
        xmlstr += "             </Borders>";
        xmlstr += "             <Font FontName=\"宋体\" CharSet=\"134\" Size=\"10\"/>";
        xmlstr += "         </Style>";
        xmlstr += "         <Style ID=\"cell_1\" >";
        xmlstr += "             <Alignment Horizontal=\"Center\" Vertical=\"Center\"  WrapText=\"1\"/>";
        xmlstr += "             <Borders>";
        xmlstr += "                 <Border Position=\"Bottom\"  LineStyle=\"Continuous\" Weight=\"1\"/>";
        xmlstr += "                 <Border Position=\"Left\" LineStyle=\"Continuous\" Weight=\"1\"/>";
        xmlstr += "                 <Border Position=\"Right\" LineStyle=\"Continuous\"  Weight=\"1\"/>";
        xmlstr += "                 <Border Position=\"Top\" LineStyle=\"Continuous\" Weight=\"1\"/>";
        xmlstr += "             </Borders>";
        xmlstr += "             <Font FontName=\"宋体\" CharSet=\"134\" Color=\"#000000\" />";
        xmlstr += "             <Interior/>";
        xmlstr += "         </Style>";
        xmlstr += "         <Style ID=\"cell_3\">";
        xmlstr += "             <Alignment  Vertical=\"Center\" WrapText=\"1\"/>";
        xmlstr += "             <Borders>";
        xmlstr += "                 <Border Position=\"Bottom\"  LineStyle=\"Continuous\" Weight=\"1\"/>";
        xmlstr += "                 <Border Position=\"Left\" LineStyle=\"Continuous\" Weight=\"1\"/>";
        xmlstr += "                 <Border Position=\"Right\" LineStyle=\"Continuous\"  Weight=\"1\"/>";
        xmlstr += "                 <Border Position=\"Top\" LineStyle=\"Continuous\" Weight=\"1\"/>";
        xmlstr += "             </Borders>";
        xmlstr += "             <Font FontName=\"宋体\" CharSet=\"134\" Color=\"#000000\" />";
        xmlstr += "             <Interior/>";
        xmlstr += "         </Style>";
        xmlstr += "         <Style ID=\"cell_2\">";
        xmlstr += "             <Alignment Vertical=\"Center\" WrapText=\"1\"/>";
        xmlstr += "             <Font FontName=\"宋体\" CharSet=\"134\" Color=\"#000000\"/>";
        xmlstr += "             <Interior/>";
        xmlstr += "             <NumberFormat Format=\"0.0\"/>";
        xmlstr += "         </Style>";
        xmlstr += "</StyleSheet>";
		
		// - 报表头（总头）
        xmlstr += "<Title>";
        xmlstr += "     <Row Height=\"28\" >";
        xmlstr += "         <Cell MergeAcross=\"10\" StyleID=\"header\" >";
        xmlstr += "             <Data Type=\"String\">单车油耗统计表</Data>";
        xmlstr += "         </Cell>";
        xmlstr += "     </Row>";
        // - 报表头（分部）
        xmlstr += "     <Row Height=\"30\" >";
        xmlstr += "         <Cell StyleID=\"title\">";
        xmlstr += "             <Data Type=\"String\">序号</Data>";
        xmlstr += "         </Cell>";
        xmlstr += "         <Cell StyleID=\"title\">";
        xmlstr += "             <Data Type=\"String\">车辆牌号</Data>";
        xmlstr += "         </Cell>";
        xmlstr += "         <Cell StyleID=\"title\">";
        xmlstr += "             <Data Type=\"String\">车架号</Data>";
        xmlstr += "         </Cell>";
        xmlstr += "         <Cell StyleID=\"title\">";
        xmlstr += "             <Data Type=\"String\">加油日期</Data>";
        xmlstr += "         </Cell>";
        xmlstr += "         <Cell StyleID=\"title\">";
        xmlstr += "             <Data Type=\"String\">初期加油里程</Data>";
        xmlstr += "         </Cell>";
        xmlstr += "         <Cell StyleID=\"title\">";
        xmlstr += "             <Data Type=\"String\">本次里程</Data>";
        xmlstr += "         </Cell>";
        xmlstr += "         <Cell StyleID=\"title\">";
        xmlstr += "             <Data Type=\"String\">加油数量（升）</Data>";
        xmlstr += "         </Cell>";
        xmlstr += "         <Cell StyleID=\"title\">";
        xmlstr += "             <Data Type=\"String\">油耗统计</Data>";
        xmlstr += "         </Cell>";
        xmlstr += "         <Cell StyleID=\"title\">";
        xmlstr += "             <Data Type=\"String\">加油员</Data>";
        xmlstr += "         </Cell>";
        xmlstr += "         <Cell StyleID=\"title\">";
        xmlstr += "             <Data Type=\"String\">驾驶员</Data>";
        xmlstr += "         </Cell>";
        xmlstr += "         <Cell StyleID=\"title\">";
        xmlstr += "             <Data Type=\"String\">登记人</Data>";
        xmlstr += "         </Cell>";
        xmlstr += "     </Row>";
        xmlstr += "</Title>";

		// 内容
        xmlstr += "<Contents>";
        var Total_Mileage=0;
        var Oil_Number=0;
        for(var i=0;i<res.length;i++){
        	if(Number(res[i].Total_Mileage)>0){
        		Total_Mileage +=Number(res[i].Total_Mileage);
        	    Oil_Number +=Number(res[i].Oil_Number);
        	}
			xmlstr += "     <Row Height=\"30\" >";
	        xmlstr += "         <Cell StyleID=\"cell_1\">";
	        xmlstr += "             <Data Type=\"Number\">"+(i+1)+"</Data>";
	        xmlstr += "         </Cell>";
	        xmlstr += "         <Cell StyleID=\"cell_1\">";
	        xmlstr += "             <Data Type=\"String\">"+res[i].ID+"</Data>";
	        xmlstr += "         </Cell>";
	        xmlstr += "         <Cell StyleID=\"cell_1\">";
	        xmlstr += "             <Data Type=\"String\">"+res[i].VIN_NO+"</Data>";
	        xmlstr += "         </Cell>";
	        xmlstr += "         <Cell StyleID=\"cell_1\">";
	        xmlstr += "             <Data Type=\"String\">"+res[i].Date+"</Data>";
	        xmlstr += "         </Cell>";
	        xmlstr += "         <Cell StyleID=\"cell_1\">";
	        xmlstr += "             <Data Type=\"Number\">"+res[i].First_Refueling_Mileage+"</Data>";
	        xmlstr += "         </Cell>";
	        xmlstr += "         <Cell StyleID=\"cell_1\">";
	        xmlstr += "             <Data Type=\"Number\">"+res[i].Total_Mileage+"</Data>";
	        xmlstr += "         </Cell>";
	        xmlstr += "         <Cell StyleID=\"cell_1\">";
	        xmlstr += "             <Data Type=\"Number\">"+res[i].Oil_Number+"</Data>";
	        xmlstr += "         </Cell>";
	        xmlstr += "         <Cell StyleID=\"cell_1\">";
	        if((Number(res[i].Total_Mileage))==0){
	        	xmlstr += "             <Data Type=\"String\">-</Data>";
	        }else{
	        	xmlstr += "             <Data Type=\"Number\">"+res[i].Oil_Number/res[i].Total_Mileage+"</Data>";
	        }
	        xmlstr += "         </Cell>";
	        xmlstr += "         <Cell StyleID=\"cell_1\">";
	        xmlstr += "             <Data Type=\"String\">"+res[i].Oil_Person+"</Data>";
	        xmlstr += "         </Cell>";
	        xmlstr += "         <Cell StyleID=\"cell_1\">";
	        xmlstr += "             <Data Type=\"String\">"+res[i].Driver+"</Data>";
	        xmlstr += "         </Cell>";
	        xmlstr += "         <Cell StyleID=\"cell_1\">";
	        xmlstr += "             <Data Type=\"String\">"+res[i].Registrant+"</Data>";
	        xmlstr += "         </Cell>";
	        xmlstr += "     </Row>";
		}
        if(Client.flag==true){
        	xmlstr += "     <Row Height=\"30\" >";
	        xmlstr += "         <Cell StyleID=\"cell_1\" MergeAcross=\"4\">";
	        xmlstr += "             <Data Type=\"String\">合计:</Data>";
	        xmlstr += "         </Cell>";
	        xmlstr += "         <Cell StyleID=\"cell_1\">";
	        xmlstr += "             <Data Type=\"Number\">"+Total_Mileage+"</Data>";
	        xmlstr += "         </Cell>";
	        xmlstr += "         <Cell StyleID=\"cell_1\">";
	        xmlstr += "             <Data Type=\"Number\">"+Oil_Number.toFixed(2)+"</Data>";
	        xmlstr += "         </Cell>";
	        xmlstr += "         <Cell StyleID=\"cell_1\">";
	        if(Total_Mileage==0){
	        	xmlstr += "             <Data Type=\"String\">-</Data>";
	        }else{
	        	xmlstr += "             <Data Type=\"Number\">"+(Oil_Number/Total_Mileage).toFixed(2)+"</Data>";
	        }
	        xmlstr += "         </Cell>";
	        xmlstr += "         <Cell StyleID=\"cell_1\" MergeAcross=\"2\">";
	        xmlstr += "             <Data Type=\"String\"></Data>";
	        xmlstr += "         </Cell>";
	        xmlstr += "     </Row>";
        }
		xmlstr += "</Contents>"
        xmlstr += "</Root>";
        $("#excelcontent").val(xmlstr);
        $("#excelform").submit();
	}
}
